[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
glib = "0.6"
gio = "0.5"
gdk = "0.9"
gtk = "0.5"
cairo-rs = "0.5"
lazy_static = "1.0"
num-complex = "0.2"
