[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
glib = "0.10"
gio = "0.9"
gdk = "0.13"
gtk = "0.9"
cairo-rs = "0.9"
lazy_static = "1.0"
num-complex = "0.3"
rayon = "1.0"
