[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
gtk = { package = "gtk4", version = "0.7" }
num-complex = "0.4"
rayon = "1.0"
once_cell = "1"
