[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
glib = "0.8"
gio = "0.7"
gdk = "0.11"
gtk = "0.7"
cairo-rs = "0.7"
lazy_static = "1.0"
num-complex = "0.2"
rayon = "1.0"
